---
title: "Markov Language Chains"
author: "Kylei Hoffland, Camille Kich, Brandon Winder, Alex Mix"
date: "5/13/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(stringr)
library(tm)
library(lubridate)
library(tidytext)
```

## Review Collection and Cleaning

Reviews for wine less than $15

```{r}
# 1094 pages with useful reviews
pre <- "https://www.winespectator.com/dailypicks/category/catid/1/page/"
post <- 1:200
links <- paste(pre, post, sep = "")
links <- as.data.frame(links)
```

```{r}
gather_reviews <- function(url) {
  page <- read_html(url)
  reviews <- html_nodes(page, ".mr-md-32")
  reviews <- html_text(reviews, trim = TRUE)
  
# Splits the long string of all reviews into separate reviews (using the date as the splitter)
  dates <- str_extract_all(reviews, "(.){4}\\s(\\d{2}),\\s(\\d{4})")
  reviews <- str_split(reviews, "(.){4}\\s(\\d{2}),\\s(\\d{4})")
  
# Adds date back to review and converts to vector
  dates <- unlist(dates)
  dates <- str_c(dates, " ")
  reviews <- unlist(reviews)
  reviews <- reviews[-1]
  reviews <- str_trim(reviews)
  reviews <- str_c(dates, reviews)
}

# Get reviews for every link and then convert to a data frame with one review per row
all_reviews <- apply(links, 1, gather_reviews) %>% as.data.frame()
all_reviews <- pivot_longer(all_reviews, V1:V200, values_to = "Reviews")
all_reviews <- all_reviews[, -1]
```

```{r}
# Convert to strings, remove extra garbage (\n and spaces, spaces > 4 replaced by '~')
all_reviews[] <- lapply(all_reviews, as.character)

for (i in 1:1000) {
  all_reviews[i,1] <- str_replace_all(all_reviews[i,1], "[\n]", "")
  all_reviews[i,1] <- str_replace_all(all_reviews[i,1], "\\s{4,}", "~")
}

# Seperate into columns by date/rating/name and type/review (seperation character is '~')
all_reviews <- all_reviews %>% separate(Reviews, c("Date", "Score", "Maker", "Name", "Price", "Review", "Reviewer"), sep = "~", extra = "merge")
all_reviews <- all_reviews %>% separate(Date, c("Date", "Score"), sep = -2, remove = FALSE)
```

```{r}
# Creates a variable for the last 2 sentences
all_reviews <- all_reviews %>% mutate(last2 = " ")

# Loops for each wine review and extracts the last 2 sentences and puts it into the variable last2
for (i in 1:1000){
  x <- str_locate(all_reviews$Review[i], "Drink")
  all_reviews$last2[i] <- str_sub(all_reviews$Review[i], start = x[1])
}

# Removes the last two sentences from Review
all_reviews <- all_reviews %>% mutate(Review = str_remove(Review, last2))

# Removes the rows that contain NA values
all_reviews <- na.omit(all_reviews)

# Seperates the last2 variable into Drink, Cases and Extra
all_reviews <- all_reviews %>% separate(last2, c("Drink", "Cases", "Extra"), sep = "\\. ", fill = "right")

# Determines which rows have additional pieces in the last 2 sentences
extra <- which(complete.cases(all_reviews))

# Removes the rows that have additional pieces in the last 2 sentences 
all_reviews <- all_reviews[-extra, ]

# Removes the variable Extra which contains all NA values
all_reviews <- subset(all_reviews, select = -Extra)
```

```{r}
# Removes the dollar sign from the price variable and makes it numeric.
all_reviews <- all_reviews %>% mutate(Price = as.numeric(str_remove_all(Price, "\\$")))

# Turns the date variable from a character into a Date
all_reviews <- all_reviews %>% mutate(Date = mdy(Date))

# Replaces the dashes in Names with a space
all_reviews <- all_reviews %>% mutate(Name = str_replace_all(Name, "-", " "))

# Removes the dashes in front of the Reviewer
all_reviews <- all_reviews %>% mutate(Reviewer = substring(Reviewer, 2))

# Seperates the punctuation under the Review variable by adding a space before and after the punctuation.
all_reviews <- all_reviews %>% mutate(Review = str_replace_all(Review, ",", " ,")) %>% mutate(Review = str_replace_all(Review, "\\.", " .")) %>% mutate(Review = str_replace_all(Review, "-", " - "))

# Seperates the punctuation under the Cases variable by adding a space before and after the punctuation.
all_reviews <- all_reviews %>% mutate(Cases = str_replace_all(Cases, ",", " , ")) %>% mutate(Cases = str_replace_all(Cases, "\\.", " .")) %>% mutate(Cases = str_replace_all(Cases, "-", " - "))
```


## Markov Chain Review Generation Function

```{r}
# Split words into pairs
review_w <- all_reviews["Review"]
review_w <- review_w %>% unnest_tokens(words, Review, token = "words", strip_punct = FALSE)
word_2 <- review_w[-1,1]
rows <- nrow(word_2) + 1
word_2[rows,1] = " "
word_3 <- word_2[-1,1]
word_3[rows,1] = " "
review_w <- cbind(review_w, word_2)
colnames(review_w) <- c("Word 1", "Word 2")

pairs <- review_w
```

```{r}
# Finds all unique words
test <- all_reviews["Review"]
test2 <- test %>% unnest_tokens(words, Review, token = "words", strip_punct = FALSE)
unique <- test2 %>% distinct()
```

```{r}
# Build lists with probabilities initialized to 0
build_list <- function(word) {
  init <- replicate(nrow(unique), 0)
  probs <- data.frame(start = init)
  colnames(probs) <- word
  row.names(probs) <- unlist(unique)
  return(probs)
}

probabilities <- apply(unique, 1, build_list)
names(probabilities) <- unlist(unique)

# Counts each occurence of word pairs
for(i in 1:nrow(pairs)) {
  probabilities[[pairs$`Word 1`[i]]][pairs$`Word 2`[i], pairs$`Word 1`[i]] <- probabilities[[pairs$`Word 1`[i]]][pairs$`Word 2`[i], pairs$`Word 1`[i]] + 1
}

#Find total times first word appears
totals <- lapply(probabilities, function(x) { sum(x, na.rm=TRUE)})
names(totals) <- unlist(unique)

# Finds new probabilities (word pair count/first word count)
for(i in 1:length(probabilities)) {
  probabilities[[i]] <- probabilities[[i]] / totals[names(probabilities)[i]]
}

# Removes extra cell from "." probabiltiies--not sure why it's there yet
probabilities[["."]] <- probabilities[["."]][-nrow(probabilities[["."]]),]
```

Here's a spot for the function

```{r}
# Builds a review
# Start word is the starting word for the review, num_sentences is the number of sentences the review should have, transition_probs is the probability table for the starting word
generate_review <- function(start_word, num_sentences, prob_list) {
  # Set up variables for the review being generated and the total sentences generated
  review <- start_word
  # transition_probs <- prob_table[[start_word]]
  total_sent <- 0
  
  # While the number of sentences generated is less than number of sentences desiered, continue building sentences
  while(total_sent < num_sentences) {
    result <- build_sentence(start_word, prob_list, review)
    total_sent <- total_sent + result[[1]]
    review <- result[[2]]
    start_word <- review[length(review)]
    # transition_probs <- probabilities[["."]]
  }
  
  # Capitalize first word and words after periods
  review[1] <- str_to_title(review[1])
  ends <- which(review == ".") + c(1)
  ends <- ends[-length(ends)]
  review[ends] <- str_to_title(review[ends])
  
  # Join vector into one string
  review <- str_c(review, collapse = " ")
  return(review)
}

# Builds a single sentence for a review.
# `start_word` is the current state, transition_probs is the probability table for the start word, gen_review is the sentence currently being generated
# Helper to the generate_review function
build_sentence <- function(start_word, prob_list, gen_review) {
  # Picks next word by sampling from all unique words with proability determind by our probability table
  transition_probs <- prob_list[[start_word]]
  next_word <- sample(unlist(unique), 1, prob=unname(unlist(transition_probs)))
  
  # Adds the next word onto the review
  gen_review <- c(gen_review, next_word)
  
  # If we generate a period (end of sentence), return the sentence. If not, continue building the sentence
  if(next_word == ".") {
    return(list(1, gen_review))
  }
  else {
    build_sentence(next_word, prob_list, gen_review)
  }
}

#Adds a variable `First` that gets the first word or every review
all_reviews <- all_reviews %>% mutate(First = word(all_reviews$Review, 1))
# Start words are all available beginning words besides punctuation 
start_words <- paste(all_reviews$First)
start_words <- unique(start_words)

#start_words <- unlist(unique) %>% removePunctuation()
#start_words <- start_words[-(which(start_words==""))]

# Generates 100 reviews with a random start word
generated_reviews <- replicate(100, generate_review(sample(start_words, 1), 2, probabilities))
generated_reviews <- as.data.frame(generated_reviews)
names(generated_reviews)[1] <- "Reviews"

# Removes extra spaces from reviews generated 
generated_reviews <- generated_reviews %>% mutate(Reviews = str_replace_all(Reviews, " ,", ",")) %>% mutate(Reviews = str_replace_all(Reviews, " \\.", ".")) %>% mutate(Reviews = str_replace_all(Reviews, " - ", "-"))
```

```{r}
# Creates dataframe for words in second order markov chain
review_second <- unite(review_w, "part_1", sep = " ")
review_second <- cbind(review_second, word_3)
colnames(review_second) <- c("Part 1", "Word 3")
pairs_2 <- review_second

# Finds the unique words of 'Part 1'
unique2 <- review_second %>% distinct(`Part 1`)
```

```{r}
# Creates large list of probabilities for each combination of second order markov chain
probabilities_2 <- apply(unique2, 1, build_list )
names(probabilities_2) <- unlist(unique2)

# Counts each occurence of word pairs
for(i in 1:nrow(pairs_2)) {
  probabilities_2[[pairs_2$`Part 1`[i]]][pairs_2$`Word 3`[i], pairs_2$`Part 1`[i]] <- probabilities_2[[pairs_2$`Part 1`[i]]][pairs_2$`Word 3`[i], pairs_2$`Part 1`[i]] + 1
}

# Find total times first word appears
totals <- lapply(probabilities_2, function(y) { sum(y, na.rm=TRUE)})
names(totals) <- unlist(unique2)

# Finds new probabilities (word pair count/first word count)
for(i in 1:length(probabilities_2)) {
  probabilities_2[[i]] <- probabilities_2[[i]] / totals[names(probabilities_2)[i]]
}
```

## Generate second order chain reviews
```{r}
# This doesn't work yet
all_reviews <- all_reviews %>% mutate(First_Sec = word(all_reviews$Review, 1, 2))

first_two <- paste(all_reviews$First_Sec)
first_two <- unique(first_two)

generated_reviews2 <- replicate(100, generate_review(sample(first_two, 1), 2, probabilities_2))
#generated_reviews2 <- as.data.frame(generated_reviews2)
#names(generated_reviews2)[1] <- "Reviews"
```


## Spruce It Up and Then Spruce It Up More

Do that here

```{r}
# Greates additional variables for the generated review that gives each review a date, price, score, when to drink and how many cases were made 
generated_reviews <- generated_reviews %>% mutate(Price = "", Score = "", Drink = "", Cases = "", Date = "")

for(i in 1:length(generated_reviews$Reviews)){
  generated_reviews$Price[i] <- sample(all_reviews$Price, 1)
  generated_reviews$Score[i] <- sample(all_reviews$Score, 1)
  generated_reviews$Drink[i] <- sample(all_reviews$Drink, 1)
  generated_reviews$Cases[i] <- sample(all_reviews$Cases, 1)
  generated_reviews$Date[i] <- as.character(sample(all_reviews$Date, 1))
}

# Removes extra spaces from cases generated 
generated_reviews <- generated_reviews %>% mutate(Cases = str_replace_all(Cases, " , ", ",")) %>% mutate(Cases = str_replace_all(Cases, " \\.", ".")) %>% mutate(Cases = str_replace_all(Cases, " - ", "-"))

# Adds dollar sign to price 
generated_reviews <- generated_reviews %>% mutate(Price = paste("$", generated_reviews$Price, sep = ""))

# Adds when to drink and cases made to reviews
generated_reviews <- generated_reviews %>% mutate(Reviews = paste(Reviews, Drink, ".", Cases, sep = " "))
generated_reviews <- generated_reviews %>% mutate(Reviews = str_replace_all(Reviews, " . ", ". "))

# Adds date, score and price to the reviews to mimic original reviews
generated_reviews <- generated_reviews %>% mutate(Reviews = paste(Date, ", Score: ", Score, ", ", Price, ", ", Reviews, sep = ""))
generated_reviews <- generated_reviews %>% select(Reviews)
```

